name = "stadia-maps-proxy"
main = "src/index.ts"
compatibility_date = "2025-06-03"

routes = [
    { pattern = "stadia-maps-proxy.ente.io", custom_domain = true }
]

tail_consumers = [
    { service = "tail" }
]

[vars]
# Added as a secret via the Cloudflare dashboard
# STADIA_API_KEY = ""